training step 1
DanCristian15/training-project pull request #1
Opened 2021-10-27 11:40 UTC by DanCristian15

2021-10-27 11:57 UTC, ionutt requested changes

2021-10-27 11:57 UTC, ionutt commented on src/Button.vue
> +  <slot></slot><p> {{text}} </p><slot></slot>
Esti pe directia buna cu sloturile.

Daca eu doresc sa pun doar icoana la stanga ... nu pot. Read putin named slots...

2021-10-27 11:57 UTC, ionutt commented on src/Button.vue
> +       eventEmit( ) {
Name-ull ii foarte confuz..
Eu folosesc componenta x...si ea are eventul "eventEmited". Spunemi doar citind aces text ce intelegi, la ce se refera acest event.
Daca de exemplu redenumesti in "click" deja iti dai seama ce face. 
Eventul de click..... nu trimite nimic, butonul nu are ce sa trimita.

2021-10-27 11:57 UTC, ionutt commented on src/Button.vue
> +.darkmode {
Aici.... ai clasa dark si light....no need to use suffix mode.

2021-10-27 12:27 UTC, adoritanagy commented on README.md
> +# components-project-2
rename in readme and name it training-project

2021-10-27 12:27 UTC, adoritanagy commented on package.json
> +  "name": "components-project-2",
rename to training-project, same as the repository name

2021-10-27 12:27 UTC, adoritanagy commented on src/Button.vue
> +<div>
Please indent properly the HTML
Use also indentation when writing properties or attributes on a certain tag. For example for the button tag below indent also the properties and attributes

2021-10-27 12:27 UTC, adoritanagy commented on src/Button.vue
> +            require: true
This doesn't work. you didn't define it correctly. please research how you should write this in the correct way.

2021-10-27 12:27 UTC, adoritanagy commented on src/Button.vue
> +            default: 20
Always when creating a prop, define also a type on it. This will help in avoiding bugs.
Define type on every prop where you didn't do it.

2021-10-27 12:27 UTC, adoritanagy commented on src/Button.vue
> +            type: Boolean
It will help if you define a default value on the prop. If by mistake when creating a new instance of the component you forget to add dark prop on it, you might have issues/bugs. Try it out to see if now you have issues.

2021-10-27 12:27 UTC, adoritanagy commented on src/Button.vue
> +  <slot></slot><p> {{text}} </p><slot></slot>
Slots should be named as in requirement, and used properly. Please research how to use named slots.

2021-10-27 12:27 UTC, adoritanagy commented on src/App.vue
> +      <buton
When creating a new component, try to avoid using already reserved names. You might end up with issues/bugs. For example, button is already a reserved name as HTML tag. Rename your component.

2021-10-27 12:27 UTC, adoritanagy commented on src/App.vue
> +      :text="btnText"
Indent properties and attributes of the button component. 
Indentation helps to have a more readable and beautiful code

2021-10-27 14:26 UTC, ionutt requested changes

2021-10-27 14:26 UTC, ionutt commented on src/Button.vue
> +            this.$emit( 'click' , {
replace with this.$emit( 'click' ). No need to send an parameter

2021-10-27 14:37 UTC, ionutt commented on src/Button.vue
> +            this.$emit( 'click' , {
hai sa reformulez, totul cu o intrebare


Poti sa ne spui, care este motivul pentru care tu trimiti acel parametru? Poate cumva gresesc eu.

2021-10-28 09:02 UTC, DanCristian15 commented on src/Button.vue
> +            this.$emit( 'click' , {
din explicatia lui am inteles ca trebuie sa aiba neaparat ca atribute numele si un obiect returnat si credeam ca e obligatoriu.

2021-10-28 13:08 UTC, merged